server:
  port: 7001 # 端口
spring:
  application:
    name: zuul # 实例名称 唯一标识
eureka:
  client:
    service-url: # 注册中心地址
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes: #自定义路由映射 (路由不能重复，下面会把上面的覆盖)
    eureka-client-producer: /api/producer/**
    eureka-client-consumers: /api/consumer/**
  # 忽略的服务
  ignored-patterns: /*-producer/**
#  敏感的头信息 默认Cookie是不能通过网关头信息传递的
#  sensitive-headers:

# 日志配置
logging:
  file: logs/${spring.application.name}/${spring.application.name}-log.log
  level:
    com.george: debug #debug 是日志的级别，com.george是包名
    root: info
